version: 2

project_name: sinkzone

force_token: github

before:
  hooks:
    - go mod download

builds:
  - binary: sinkzone
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
    flags:
      - -trimpath

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    formats:
      - binary

checksum:
  name_template: checksums.txt

changelog:
  use: github

brews:
  - name: sinkzone
    description: A strict DNS filter to help you stay focused — or keep your kids safe
    homepage: https://github.com/berbyte/sinkzone
    license: MIT
    repository:
      owner: berbyte
      name: homebrew-tap
      token: "{{ .Env.GH_PAT }}"

# Docker images
dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:latest-amd64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
    dockerfile: Dockerfile.releaser
    extra_files:
      - docs/sinkzone.1
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-arm64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:latest-arm64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    dockerfile: Dockerfile.releaser
    extra_files:
      - docs/sinkzone.1
    goarch: arm64


docker_manifests:
  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}-arm64"
  - name_template: "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:latest"
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:latest-amd64"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:latest-arm64"
