# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sinkzone < Formula
  desc "A strict DNS filter to help you stay focused — or keep your kids safe"
  homepage "https://github.com/berbyte/sinkzone"
  version "0.0.17"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/berbyte/sinkzone/releases/download/v0.0.17/sinkzone_Darwin_x86_64.tar.gz"
      sha256 "22bd06ef41eaeb023fd0843900fabf0d6f7898dbf4dbbffd1bad88aee508544a"

      def install
        bin.install "sinkzone"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/berbyte/sinkzone/releases/download/v0.0.17/sinkzone_Darwin_arm64.tar.gz"
      sha256 "c1afbc1a5d92ff361e599b58291c56fb37a2c75878957911e5995799e684d059"

      def install
        bin.install "sinkzone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/berbyte/sinkzone/releases/download/v0.0.17/sinkzone_Linux_x86_64.tar.gz"
      sha256 "8e81969300878d8c78180321e4667cdf1c4f6ccb8fe136d7813043f13013d328"
      def install
        bin.install "sinkzone"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/berbyte/sinkzone/releases/download/v0.0.17/sinkzone_Linux_arm64.tar.gz"
      sha256 "84c1493d00709aebcd7f888d6ec8944a2429c327c8a2fd48b35ec7e3b460f6b4"
      def install
        bin.install "sinkzone"
      end
    end
  end
end
